classifier:
  name: CLDFD
  kwargs:
    feat_dim: 512
    num_class: 64
    batch_size: 32
    gamma: 1 # 计算总损失时蒸馏损失的占比
    alpha: 0
    is_distill: True
    emb_func_path: ./results/CLDFD_PreTrain-miniImageNet--ravi-ResNet10-5-1-Dec-05-2024-22-43-16/checkpoints/model_best.pth
    # 特征去噪部分参数
    feature_denoising:
      enable: True
      top_k: 10
    # 数据增强需要的裁剪大小
    pic_size: 224
    # 使用的数据增强类型，分为ImageNet、CIFAR10、SVHN、SubPolicy
    transform_type: ImageNet
    # 自监督损失相关
    feature_dim: 512
    ss_proj_dim: 128
    temperature: 1
    # epoch数，用于kdloss计算时使用
    epoch: 60

