includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/CLDFD_pretrain.yaml
  - backbones/resnet10.yaml


device_ids: 0
n_gpu: 1
batch_size: 32
#augment_method: DeepBdcAugment
way_num: 5
shot_num: 1
query_num: 15
# episode_size: 1
# train_episode: 100
#test_episode: 600
#train_episode: 100
test_episode: 100

classifier:
  name: CLDFD_PreTrain
  kwargs:
#    inner_param:
#      inner_optim:
#        name: Adam
#        kwargs:
#          lr: 1e-3
#      inner_train_iter: 100
#      inner_batch_size: 4
    feat_dim: 512
    num_class: 64

backbone:
  name: ResNet10
  kwargs:
#    keep_prob: 0.0
#    avg_pool: True
#    is_flatten: True
#    maxpool_last2: True
    flatten: True


optimizer:
  name: SGD
  kwargs:
    lr: 0.1
    momentum: 0.9
    weight_decay: 1e-4
    nesterov: False
  other: ~
    # emb_func: 0.001 # define lr OR
    # another_part:    # define multi params
    #   lr: 0.1
    #   weight_decay: 0.5


# lr_scheduler info
lr_scheduler:
#  name: StepLR
#  kwargs:
#    gamma: 0.1
#    step_size: 30
  name: MultiStepLR # 这是原本cldfd使用的学习率调整器
  kwargs:
    gamma: 0.1
    milestones: [30,50]
    last_epoch: -1

warmup: 0 # set 0 to turn off warmup
seed: 42
# backbone:
#   name: resnet12
#   kwargs:
#     keep_prob: 0.0

# backbone:
#   name: resnet18
#   kwargs:

# backbone:
#   name: WRN
#   kwargs:
#     depth: 10
#     widen_factor: 10
#     dropRate: 0.0
#     avg_pool: True
#     is_flatten: True

