includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/CLDFD.yaml
  - backbones/resnet10.yaml


device_ids: 0
n_gpu: 1
batch_size: 32
#augment_method: DeepBdcAugment
way_num: 5
shot_num: 1
query_num: 15
# episode_size: 1
# train_episode: 100
#test_episode: 600
#train_episode: 100
test_episode: 100

classifier:
  name: CLDFD
  kwargs:
    feat_dim: 512
    num_class: 64
    batch_size: 32
    gamma: 1 # 计算总损失时蒸馏损失的占比
    alpha: 0
    is_distill: True
    emb_func_path: ./results/CLDFD_PreTrain-miniImageNet--ravi-ResNet10-5-1-Dec-05-2024-22-43-16/checkpoints/emb_func_best.pth
    # 特征去噪部分参数
    feature_denoising:
      enable: True
      top_k: 10
    # 数据增强需要的裁剪大小
    pic_size: 224
    # 使用的数据增强类型，分为ImageNet、CIFAR10、SVHN、SubPolicy
    transform_type: ImageNet
    # 自监督损失相关
    feature_dim: 512
    ss_proj_dim: 128
    temperature: 1
    # epoch数，用于kdloss计算时使用
    epoch: 60





backbone:
  name: ResNet10
  kwargs:
#    keep_prob: 0.0
#    avg_pool: True
#    is_flatten: True
#    maxpool_last2: True
    flatten: True


optimizer:
  name: SGD
  kwargs:
    lr: 0.1
    momentum: 0.9
    weight_decay: 1e-4
    nesterov: False
  other: ~
    # emb_func: 0.001 # define lr OR
    # another_part:    # define multi params
    #   lr: 0.1
    #   weight_decay: 0.5


# lr_scheduler info
lr_scheduler:
#  name: StepLR
#  kwargs:
#    gamma: 0.1
#    step_size: 30
  name: MultiStepLR # 这是原本cldfd使用的学习率调整器
  kwargs:
    gamma: 0.1
    milestones: [30,50]
    last_epoch: -1

warmup: 0 # set 0 to turn off warmup
seed: 42
# backbone:
#   name: resnet12
#   kwargs:
#     keep_prob: 0.0

# backbone:
#   name: resnet18
#   kwargs:

# backbone:
#   name: WRN
#   kwargs:
#     depth: 10
#     widen_factor: 10
#     dropRate: 0.0
#     avg_pool: True
#     is_flatten: True

